services:
  mysqlserverviii:
    container_name: mysqlserverviii
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: shuja
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql8:/var/lib/mysql
    networks:
      - database
  mysqlserverv:
    container_name: mysqlserverv
    image: mysql:5.7
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    ports:
      - 33060:3306
    environment:
      MYSQL_USER: shuja
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql5:/var/lib/mysql
    networks:
      - database
networks:
  database:
    external: true
