services:
  mysqlserverviii:
    container_name: mysqlserverviii
    image: mysql:8.4
    ports:
      - '${MYSQL_8_PORT:-3306}:3306'
    environment:
      MYSQL_USER: ${MYSQL_8_USER:-shuja}
      MYSQL_PASSWORD: ${MYSQL_8_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_8_ROOT_PASSWORD:-secret}
    volumes:
      - ./mysql8:/var/lib/mysql
    networks:
      - database
  mysqlserverv:
    container_name: mysqlserverv
    image: mysql:5.7
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    ports:
      - '${MYSQL_5_PORT:-33060}:3306'
    environment:
      MYSQL_USER: ${MYSQL_5_USER:-shuja}
      MYSQL_PASSWORD: ${MYSQL_5_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_5_ROOT_PASSWORD:-secret}
    volumes:
      - ./mysql5:/var/lib/mysql
    networks:
      - database
networks:
  database:
    external: true
